### PR TITLE
Use babel-plugin-lodash

### PR DESCRIPTION
**Pull request by hasnat**
Use babel-plugin-lodash to not include unnecessary lodash functions

### CODE REVIEW

**Comment by gajus** [comment]
Whats the use case? it is a server-side script.

**Comment by hasnat** [comment]
only that I am trying to reduce my application bundle file size for both client and server side scripts.

**Comment by gajus** [comment]
> only that I am trying to reduce my application bundle file size for both client and server side scripts.

Whats the reason you are including table in a client-side application?

**Comment by hasnat** [comment]
sorry this is used only on server side logging, I was working on reducing bundle size for both client and server side, so this came in. Since table is using babel thought would be handy enough to add babel-plugin-lodash.

**Comment by gajus** [comment]
> sorry this is used only on server side logging, I was working on reducing bundle size for both client and server side, so this came in. Since table is using babel thought would be handy enough to add babel-plugin-lodash.

I'd rather not – it just adds an additional potential point of failure with no benefits.

Thank you for the PR.

**Pull request closed without merging**
