### PR TITLE
add typescript typings

### PR DESCRIPTION
**Pull request by evanshortiss**
This would be nice to have for people who would like to use this in their TypeScript projects.

I had an issue making this PR with the "precommit" script. It fails on eslint checks, but I've not changed any code to cause that. I'm using node 4.4.3.

### CODE REVIEW

**Comment by gajus** [comment]
Isn't there some public repository where all the TS declarations are stored?

**Comment by evanshortiss** [comment]
@gajus yep, that's correct, it's [DefinitelyTyped](github.com/DefinitelyTyped/DefinitelyTyped). Generally it's best to try add the type definition to a module's `package.typings` when possible rather than DefinitelyTyped. It's easier to keep in sync with module updates and DefinitelyTyped recommend it (can't find the link to the recommendation right now).

**Comment by evanshortiss** [comment]
@gajus any further thoughts on this one?

**Comment by gajus** [comment]
> @gajus any further thoughts on this one?

I'd like to keep TypeScript typings separate from this code base. Sorry.

Adding them here would add additional maintenance responsibility. Since I do not use TypeScript, that would potentially become a bottle neck for making future releases.

**Comment by evanshortiss** [comment]
That's cool, I've opened a PR here instead FYI: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13441

**Pull request closed without merging**
