### PR TITLE
Use Ajv

### PR DESCRIPTION
**Pull request by epoberezkin**

### CODE REVIEW

**Comment by gajus** [comment]
[v3.8.0](https://github.com/gajus/table/tree/v3.8.0) has been published. Thank you.

**Comment by epoberezkin** [comment]
Thanks!

**Comment by Arcanemagus** [comment]
Ajv apparently compiles code using `eval` preventing it from being used in environments that block this btw... this has caused https://github.com/AtomLinter/linter-stylelint/issues/269.

**Comment by epoberezkin** [comment]
@Arcanemagus Eval is replaced in Ajv version 4.7.2

**Pull request merged**
