### PR TITLE
refactor: precompile schemas, related to stylelint/stylelint#1912

### PR DESCRIPTION
**Pull request by epoberezkin**
Needs more tests, ideally test coverage in compiled schemas

### CODE REVIEW

**Comment by epoberezkin** [comment]
don't merge it yet please

**Comment by chaffeqa** [comment]
Any movement on this? many atom users are experiencing this issue

thanks a ton for submitting this @epoberezkin !

**Comment by epoberezkin** [comment]
It's not ready to be merged yet - I am working on a couple of issues and adding some tests. That ajv-pack that makes portable validation functions is a very new thing and it's nowhere near as stable as ajv itself...

Also I understand @gajus will be away for one (or two?) more weeks anyway, so I plan to make it all work and tested by then.

**Comment by epoberezkin** [comment]
@gajus, schemas are all working now. There seem to be some issues with eslint that break the tests.
I also think there should be prepublish script to make sure the latest versions of code/compiled schemas are published.

**Comment by gajus** [comment]
@epoberezkin Are you happy for this to be merged now?

**Comment by epoberezkin** [comment]
yes, please merge

**Comment by gajus** [comment]
https://github.com/gajus/table/releases/tag/v3.8.2 has been published.

**Pull request merged**
